### PR TITLE
smooth transition and +25% brand.img

### PR DESCRIPTION
**Pull request by ghost**
# navbar 
## smooth transition when scrolling
[mdn transition](https://developer.mozilla.org/en-US/docs/Web/CSS/transition)
```
/* Apply to all changed properties */
transition: all 0.5s ease-in;
```
## .navbar-brand img 
is 25% bigger (while transparent)
## .nav-link 
color: white 
shadow
Screenshot 2022-09-18 at 18 28 52

### CODE REVIEW

**Review by alvarotrujillo — APPROVED** [review]
Thanks Lucas, like the 'ease-in', it's definitely a better UX this way

**Review by onofrecc — APPROVED** [review]
Refining this thing... much better

**Comment by alvarotrujillo** [comment]
FYI - Will be sure to push to Heroku on @A-drienne 's approval too - JS can often give us a bit of issues on Heroku as we saw, so let's hope this one goes smoothly!

**Review by A-drienne — APPROVED** [review]
Looks great, I love the larger Freddie logo

**Pull request merged**
